from .usuarioview import usuarioListView, UsuarioRetrieveUpdateDeleteView
from .medicoview import MedicoListCreateView, MedicoRetrieveUpdateDeleteView
from .pacienteview import PacienteListCreateView, PacienteRetrieveUpdateDeleteView