from .enfermeroserializars import Enfermeroserializers
from .historiaserializers import Historiaclinicaserializers
from .medicoserializers import Medicoserializers
from .pacienteserialiserz import Pacienteserializers
from .usuarioserializers import Usuarioserializers