# Generated by Django 4.1.2 on 2022-10-17 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=256, verbose_name='rol')),
                ('nombre', models.CharField(max_length=256, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=256, verbose_name='Apellido')),
                ('celular', models.CharField(max_length=256, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=256, verbose_name='Direccion')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=63, verbose_name='Area')),
                ('auxiliar', models.BooleanField(default=False, verbose_name='Auxiliar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historiaclinica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oximetria', models.IntegerField(blank=True, null=True, verbose_name='Oximetria')),
                ('frecuenciaRespiratoria', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria')),
                ('frecuenciaCardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia Cardiaca')),
                ('temperatura', models.IntegerField(blank=True, null=True, verbose_name='Temperatura')),
                ('presionArterial', models.IntegerField(blank=True, null=True, verbose_name='Presion Arterial')),
                ('glicemias', models.IntegerField(blank=True, null=True, verbose_name='Glicemia')),
                ('diagnostico', models.TextField(blank=True, verbose_name='diagnostico')),
                ('cuidados', models.TextField(blank=True, verbose_name='cuidados')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Especialidad', models.CharField(max_length=50, null=True, verbose_name='Especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enfermo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalhouseapp.enfermero')),
                ('historiaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalhouseapp.historiaclinica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalhouseapp.medico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
